/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  
export declare namespace NFTMarketplace {
      
    export type ListingStruct = {seller: AddressLike, price: BigNumberish, isActive: boolean}

    export type ListingStructOutput = [seller: string, price: bigint, isActive: boolean] & {seller: string, price: bigint, isActive: boolean }
  
    }

  export interface NFTMarketplaceInterface extends Interface {
    getFunction(nameOrSignature: "BPS_DENOMINATOR" | "COMMISSION_BPS" | "buyNFT" | "cancelListing" | "getListedContracts" | "getListing" | "getListingsByContract" | "listNFT" | "owner" | "renounceOwnership" | "token" | "transferOwnership"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "ListingCancelled" | "NFTListed" | "NFTPurchased" | "OwnershipTransferred"): EventFragment;

    encodeFunctionData(functionFragment: 'BPS_DENOMINATOR', values?: undefined): string;
encodeFunctionData(functionFragment: 'COMMISSION_BPS', values?: undefined): string;
encodeFunctionData(functionFragment: 'buyNFT', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'cancelListing', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'getListedContracts', values?: undefined): string;
encodeFunctionData(functionFragment: 'getListing', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'getListingsByContract', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'listNFT', values: [AddressLike, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'token', values?: undefined): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;

    decodeFunctionResult(functionFragment: 'BPS_DENOMINATOR', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'COMMISSION_BPS', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'buyNFT', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'cancelListing', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getListedContracts', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getListing', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getListingsByContract', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'listNFT', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'token', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
  }

  
    export namespace ListingCancelledEvent {
      export type InputTuple = [seller: AddressLike, nftContract: AddressLike, tokenId: BigNumberish];
      export type OutputTuple = [seller: string, nftContract: string, tokenId: bigint];
      export interface OutputObject {seller: string, nftContract: string, tokenId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace NFTListedEvent {
      export type InputTuple = [seller: AddressLike, nftContract: AddressLike, tokenId: BigNumberish, price: BigNumberish];
      export type OutputTuple = [seller: string, nftContract: string, tokenId: bigint, price: bigint];
      export interface OutputObject {seller: string, nftContract: string, tokenId: bigint, price: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace NFTPurchasedEvent {
      export type InputTuple = [buyer: AddressLike, seller: AddressLike, nftContract: AddressLike, tokenId: BigNumberish, price: BigNumberish, commission: BigNumberish, sellerProceeds: BigNumberish];
      export type OutputTuple = [buyer: string, seller: string, nftContract: string, tokenId: bigint, price: bigint, commission: bigint, sellerProceeds: bigint];
      export interface OutputObject {buyer: string, seller: string, nftContract: string, tokenId: bigint, price: bigint, commission: bigint, sellerProceeds: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface NFTMarketplace extends BaseContract {
    
    connect(runner?: ContractRunner | null): NFTMarketplace;
    waitForDeployment(): Promise<this>;

    interface: NFTMarketplaceInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    BPS_DENOMINATOR: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    COMMISSION_BPS: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    buyNFT: TypedContractMethod<
      [_nftContract: AddressLike, _tokenId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    cancelListing: TypedContractMethod<
      [_nftContract: AddressLike, _tokenId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    getListedContracts: TypedContractMethod<
      [],
      [string[]],
      'view'
    >
    

    
    getListing: TypedContractMethod<
      [_nftContract: AddressLike, _tokenId: BigNumberish, ],
      [NFTMarketplace.ListingStructOutput],
      'view'
    >
    

    
    getListingsByContract: TypedContractMethod<
      [_nftContract: AddressLike, ],
      [[bigint[], NFTMarketplace.ListingStructOutput[]]],
      'view'
    >
    

    
    listNFT: TypedContractMethod<
      [_nftContract: AddressLike, _tokenId: BigNumberish, _price: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    renounceOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    token: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'BPS_DENOMINATOR'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'COMMISSION_BPS'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'buyNFT'): TypedContractMethod<
      [_nftContract: AddressLike, _tokenId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'cancelListing'): TypedContractMethod<
      [_nftContract: AddressLike, _tokenId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getListedContracts'): TypedContractMethod<
      [],
      [string[]],
      'view'
    >;
getFunction(nameOrSignature: 'getListing'): TypedContractMethod<
      [_nftContract: AddressLike, _tokenId: BigNumberish, ],
      [NFTMarketplace.ListingStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getListingsByContract'): TypedContractMethod<
      [_nftContract: AddressLike, ],
      [[bigint[], NFTMarketplace.ListingStructOutput[]]],
      'view'
    >;
getFunction(nameOrSignature: 'listNFT'): TypedContractMethod<
      [_nftContract: AddressLike, _tokenId: BigNumberish, _price: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'token'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'ListingCancelled'): TypedContractEvent<ListingCancelledEvent.InputTuple, ListingCancelledEvent.OutputTuple, ListingCancelledEvent.OutputObject>;
getEvent(key: 'NFTListed'): TypedContractEvent<NFTListedEvent.InputTuple, NFTListedEvent.OutputTuple, NFTListedEvent.OutputObject>;
getEvent(key: 'NFTPurchased'): TypedContractEvent<NFTPurchasedEvent.InputTuple, NFTPurchasedEvent.OutputTuple, NFTPurchasedEvent.OutputObject>;
getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;

    filters: {
      
      'ListingCancelled(address,address,uint256)': TypedContractEvent<ListingCancelledEvent.InputTuple, ListingCancelledEvent.OutputTuple, ListingCancelledEvent.OutputObject>;
      ListingCancelled: TypedContractEvent<ListingCancelledEvent.InputTuple, ListingCancelledEvent.OutputTuple, ListingCancelledEvent.OutputObject>;
    

      'NFTListed(address,address,uint256,uint256)': TypedContractEvent<NFTListedEvent.InputTuple, NFTListedEvent.OutputTuple, NFTListedEvent.OutputObject>;
      NFTListed: TypedContractEvent<NFTListedEvent.InputTuple, NFTListedEvent.OutputTuple, NFTListedEvent.OutputObject>;
    

      'NFTPurchased(address,address,address,uint256,uint256,uint256,uint256)': TypedContractEvent<NFTPurchasedEvent.InputTuple, NFTPurchasedEvent.OutputTuple, NFTPurchasedEvent.OutputObject>;
      NFTPurchased: TypedContractEvent<NFTPurchasedEvent.InputTuple, NFTPurchasedEvent.OutputTuple, NFTPurchasedEvent.OutputObject>;
    

      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    
    };
  }